# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7041bdfff25c5835b3abd975b3d5349aac8161f6bbd4ef228907f31b4c933c968281167e8dcc4e687b551e1a4374ba317f7106fdc1b7638b9fcd9cd05f77ce22

test:
  secret_key_base: d986853d78e13277682da9d746a789f6015db827fdfc8c4fe0777b457120ede2e62ace971880fbc7693085b5a55771aaba012ff4a2ffd07da9dd0b96bbcfa6ea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
